#!/usr/bin/env python3
"""Render terminal + markdown reports from a normalized findings document."""
import json
import os
import sys

ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
DISCLAIMER = ("This report is generated by automated tooling. Automated license "
              "detection is a starting point, not legal advice. Risk levels and "
              "obligation notes are heuristics that require human/legal review.")


def _sorted(findings):
    return sorted(findings, key=lambda f: ORDER.get(f.get("risk_level"), 9))


def terminal_report(doc):
    repo = doc.get("repo", {})
    lines = ["License Compliance Audit", "Repo license baseline:",
             f"- Declared license: {repo.get('declared_license', 'UNKNOWN')}",
             "- Evidence: "
             + (", ".join(repo.get("declared_license_evidence", [])) or "none"),
             "Coverage:"]
    for c in doc.get("coverage", []):
        note = f" ({c['note']})" if c.get("note") else ""
        lines.append(f"- {c.get('category')}: {c.get('status')}{note}")
    tops = [f for f in _sorted(doc.get("findings", []))
            if f.get("risk_level") in ("critical", "high")][:5]
    lines.append("Top findings:")
    if tops:
        for i, f in enumerate(tops, 1):
            lines.append(f"{i}. {f.get('risk_level', '').upper()} — "
                         f"{f.get('item')}: {f.get('unmet_obligation')}")
    else:
        lines.append("- none at critical/high")
    lines += ["Full reports:", "- license-compliance-report.md",
              "- license-compliance-findings.json"]
    return "\n".join(lines)


def _version_source_cell(f):
    version = f.get("version", "")
    source = f.get("source")
    if source:
        return f"{version} / {source}" if version else str(source)
    return str(version)


def _executive_summary(findings):
    counts = {level: 0 for level in ORDER}
    for f in findings:
        level = f.get("risk_level")
        if level in counts:
            counts[level] += 1
    counts["info"] = counts.get("info", 0)
    summary_line = ", ".join(
        f"{counts.get(level, 0)} {level}" for level in ("critical", "high", "medium", "low", "info")
    )
    total = sum(counts.values())
    return [
        f"- **Total findings:** {total}",
        f"- **By risk level:** {summary_line}",
        "- This summary is a count, not a legal verdict; see the reconciliation "
        "table and human/legal review items below.",
    ]


def markdown_report(doc):
    repo = doc.get("repo", {})
    findings = doc.get("findings", [])
    out = ["# License Compliance Report", "", f"> {DISCLAIMER}", "",
           "## Executive summary", ""]
    out += _executive_summary(findings)
    out += ["", "## Declared license baseline", "",
            f"- **License:** {repo.get('declared_license', 'UNKNOWN')}",
            "- **Evidence:** "
            + (", ".join(repo.get("declared_license_evidence", [])) or "none"),
            "", "## Coverage", ""]
    for c in doc.get("coverage", []):
        out.append(f"- **{c.get('category')}** — {c.get('status')}"
                   + (f" ({c['note']})" if c.get("note") else ""))
    out += ["", "## Reconciliation", "",
            "| Item | Type | Path/Pkg | Version/Source | License | Usage | Risk vs repo "
            "| Unmet obligation | Evidence | Confidence | Risk | Action |",
            "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for f in _sorted(findings):
        cells = [
            str(f.get("item", "")),
            str(f.get("type", "")),
            str(f.get("path", "")),
            _version_source_cell(f),
            str(f.get("license_expression", "")),
            str(f.get("usage", "")),
            str(f.get("compatibility_risk", "")),
            str(f.get("unmet_obligation", "")),
            "; ".join(f.get("evidence", [])),
            str(f.get("confidence", "")),
            str(f.get("risk_level", "")),
            str(f.get("recommended_action", "")),
        ]
        out.append("| " + " | ".join(cells) + " |")
    out += ["", "## Human / legal review items", ""]
    review = [f"- **{f.get('item')}** — {f.get('review_notes')}"
              for f in findings if f.get("review_notes")]
    out += review or ["- none"]
    out += ["", "## Limitations", "",
            "- Detection is bounded by installed scanners; gaps are reported, "
            "not guessed.",
            "- Asset/font/dataset detection is heuristic, not content "
            "fingerprinting.", "",
            "## Disclaimer", "", f"> {DISCLAIMER}", ""]
    return "\n".join(out)


def render(doc, out_dir=".", write=True):
    if write:
        with open(os.path.join(out_dir, "license-compliance-report.md"), "w") as fh:
            fh.write(markdown_report(doc) + "\n")
        with open(os.path.join(out_dir, "license-compliance-findings.json"), "w") as fh:
            json.dump(doc, fh, indent=2, sort_keys=True)
            fh.write("\n")
    return terminal_report(doc)


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    doc = json.load(open(argv[0]))
    out_dir = argv[1] if len(argv) > 1 else "."
    print(render(doc, out_dir))
    return 0


if __name__ == "__main__":
    sys.exit(main())
